---
title: "bootstrapping"
author: "Carolina Montes Garcia"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
library(SemiPar)
library(modelr)
library(mgcv)

set.seed(1)

```

Do bootstrapping

```{r}
n_samp = 250

sim_df_constant =
  tibble(
    x = rnorm(n_samp, 1, 1), 
    error = rnorm(n_samp, 0,1),
    y= 2+3*x + error
  )

sim_df_nonconstant =
  sim_df_constant %>% 
  mutate(
    error = error * .75*x,
    y= 2+3*x + error
  )

```

let's look at these

```{r}
sim_df_constant %>% 
  ggplot(aes(x = x, y = y))+
  geom_point()+
  stat_smooth(method= "lm")
```

Look at regression results

```{r}
sim_df_constant %>% 
  lm(y~x, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

## Draw a bootstrap sample

```{r}
boot_sample = function(df){
  
  boot_df = 
    sample_frac(df, replace = TRUE) %>% 
    arrange(x)
  
  return(boot_df)
}
```

lets try running this!

```{r}
sim_df_nonconstant %>% 
  boot_sample() %>% 
  ggplot(aes(x = x, y = y))+
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```

can we do this as part of an analysis


```{r}
sim_df_nonconstant %>% 
  boot_sample() %>% 
  lm(y~x, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```


## bootstrap A LOT

```{r}
boot_straps =
  tibble(
    strap_number = 1:1000
  ) %>% 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconstant)), 
    models = map(strap_sample, \(df) lm(y~x, data =df)), 
    results = map(models, broom::tidy)
  )

bootstrap_results = 
  boot_straps %>% 
  select(strap_number, results) %>% 
  unnest(results) %>% 
  group_by(term) %>% 
  summarize(
    boot_se = sd(estimate)
  ) %>% 
  knitr::kable(digits = 3)
```


## do this all using modelr

```{r}
boot_straps = 
  sim_df_nonconstant %>% 
  modelr::bootstrap(1000) %>% 
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(y~x, data = df)),
    results = map(models, broom::tidy)
  ) %>% 
    select(.id, results) %>% 
    unnest(results)
```

