---
title: "linear_models"
author: "Carolina Montes Garcia"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
```

Do some data cleaning

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars=review_scores_location/2) %>% 
  rename(
    borough = neighbourhood_group, 
    neighborhood = neighbourhood
  ) %>% 
  filter(
    borough != "State Island"
  ) %>% 
  select(price,stars,borough,neighborhood,room_type) %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```


```{r}
fit = lm(price ~ stars,data = nyc_airbnb)

summary(fit)
names(summary(fit))

coef(fit)

broom::tidy(fit)#it shows me the summary info as a tibble

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value)

fit %>% 
  broom::glance()
```

Try a bit more complex.

```{r}
fit = 
  lm(price~stars +borough, data = nyc_airbnb)

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough:")
  ) %>% 
  knitr::kable(digits = 3)

```

## Some diagnostics

(backtract to some EDA)
```{r}
nyc_airbnb %>% 
  ggplot(aes(x=stars, y=price))+
  geom_point()+
  stat_smooth(method = "lm")
```


Most diagnostics use residuals

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x=borough, y=resid))+
  geom_violin()+
  ylim(-100,100)
```

Residuals against fitted values

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x=pred, y=resid))+
  geom_point()
```

## hypothesis testing


```{r}

fit_null = lm(price~stars +borough, data = nyc_airbnb)

fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

fit_null %>% 
  broom::tidy()

fit_alt %>% 
  broom::tidy()


anova(fit_null, fit_alt) %>% 
  broom::tidy()
```


## do effects differ across boroughs

First, use a lot of interactions

```{r}
nyc_airbnb %>% 
  lm(price ~ stars * borough + room_type * borough, data = .)%>% 
  broom::tidy()

nyc_airbnb |> 
  lm(price ~ stars * borough + room_type * borough, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```


```{r}
nest_lm_res =
  nyc_airbnb |> 
  nest(data = -borough) |> 
  mutate(
    models = map(data, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy)) |> 
  select(-data, -models) |> 
  unnest(results)


nest_lm_res |> 
  select(borough, term, estimate) |> 
  mutate(term = fct_inorder(term)) |> 
  pivot_wider(
    names_from = term, values_from = estimate) |> 
  knitr::kable(digits = 3)
```

```{r}
manhattan_neighborhood_fit_df = 
nyc_airbnb %>% 
  filter(borough =="Manhattan") %>% 
  nest(data = -(borough:neighborhood)) %>% 
  mutate(
    model= map(data, \(x) lm(price~stars + room_type, data = x)),
    results = map(model, broom::tidy
  )) %>% 
  select(neighborhood, results) %>% 
  unnest(results)


```

look at the effect of room type
```{r}
manhattan_neighborhood_fit_df %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = term, y = estimate))+
  geom_boxplot()
```

```{r}
manhattan_neighborhood_fit_df %>% 
  filter(str_detect(term, "room_type")) %>% 
  filter(estimate>0)

nyc_airbnb %>% 
  filter(
    neighborhood == "NoHo",
    room_type == "Shared room"
  )
```

